# version: '3.8'

# docker compose -f ./docker-compose.backend.yml -p local-backend up -d
services:
  backend:
    image: node:20-alpine
    container_name: nestjs-api
    working_dir: /app
    volumes:
      - ${HOME}/docker-apps/backend/dist:/app
    command: npm run start:prod
    expose:
      - "8001"
    ports:
      - "8001:8001" # 测试
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/app
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=admin123
      - MINIO_USE_SSL=false
    networks:
      - backend-network
      - database-network
      - storage-network

networks:
  backend-network:
    external: true
  database-network:
    external: true
  storage-network:
    external: true
