version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: gateway-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/ssl:ro
      - certbot-webroot:/var/www/certbot:ro
    networks:
      - frontend-network
      - backend-network

  certbot:
    image: certbot/certbot
    container_name: gateway-certbot
    restart: unless-stopped
    volumes:
      - ./certs:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  certbot-webroot:

networks:
  frontend-network:
    external: true
  backend-network:
    external: true
