version: '3.8'

services:
  api:
    image: node:20-alpine
    container_name: nestjs-api
    working_dir: /app
    volumes:
      - backend-dist:/app
    command: npm run start:prod
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/app
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=admin123
      - MINIO_USE_SSL=false
    networks:
      - backend-network
      - database-network
      - storage-network

networks:
  backend-network:
    external: true
  database-network:
    external: true
  storage-network:
    external: true

volumes:
  backend-dist:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/docker-apps/backend-dist
