# version: '3.8'

# docker compose -f ./docker-compose.frontend.yml -p local-frontend up -d
# 重启服务
# docker compose -f ./docker-compose.frontend.yml -p local-frontend restart frontend
services:
  frontend:
    container_name: nginx-frontend
    image: nginx:stable
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    restart: always
    expose:
      - "80"
    # ports:
    #   - "8002:80" # 测试
    volumes:
      - ${HOME}/docker-apps/frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${HOME}/docker-apps/frontend/dist:/usr/share/nginx/html
    networks:
      - frontend-network

networks:
  frontend-network:
    external: true
