version: '3.8'

services:
  mongo:
    image: mongo:4.4
    container_name: mongodb
    volumes:
      - mongo-data:/data/db
    networks:
      - database-network

networks:
  database-network:
    external: true

volumes:
  mongo-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/docker-apps/mongo-data
