version: '3.8'

services:
  api:
    image: node:18-alpine
    container_name: nestjs-api
    working_dir: /app
    volumes:
      - backend-dist:/app
    command: npm run start:prod
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/app
      - REDIS_URI=redis://redis:6379
    networks:
      - backend-network
      - database-network

networks:
  backend-network:
    external: true
  database-network:
    external: true

volumes:
  backend-dist:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/docker-apps/backend-dist
