version: '3.8'

services:
  web:
    container_name: nginx-web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - "80"
    volumes:
      - frontend-nginx:/etc/nginx/nginx.conf:ro
      - frontend-dist:/usr/share/nginx/html
    networks:
      - frontend-network

networks:
  frontend-network:
    external: true

volumes:
  frontend-nginx:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/docker-apps/nginx/frontend.nginx.conf
  frontend-dist:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/docker-apps/frontend-dist
