# version: '3.8'

# docker compose -f ./docker-compose.backup.yml -p local-backup up -d
services:
  mongo-backup:
    image: mongo:4.4
    container_name: mongodb-backup
    volumes:
      - ${HOME}/docker-backups/mongo-backup:/data/backup
    networks:
      - database-network
    command: |
      /bin/sh -c '
      while true; do
        echo "[$(date)] Starting backup..."
        mongodump --host mongo --out /data/backup/$(date +%Y%m%d_%H%M%S)
        echo "[$(date)] Backup completed"
        sleep 24h
      done
      '

networks:
  database-network:
    external: true
