version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: gateway-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - gateway-nginx:/etc/nginx/nginx.conf:ro
      - nginx-certs:/etc/nginx/ssl:ro
      - certbot-webroot:/var/www/certbot:ro
    networks:
      - frontend-network
      - backend-network

  certbot:
    image: certbot/certbot
    container_name: gateway-certbot
    restart: unless-stopped
    volumes:
      - nginx-certs:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  gateway-nginx:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/docker-apps/nginx/gateway.nginx.conf
  nginx-certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/docker-apps/nginx/certs
  certbot-webroot:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/docker-apps/certbot-webroot

networks:
  frontend-network:
    external: true
  backend-network:
    external: true
