# version: '3.8'

# docker compose -f ./docker-compose.database.yml -p local-database up -d
# MONGO_DB_NAME=mydb docker compose -f ./docker-compose.database.yml -p local-database up -d
# mongodb://admin:admin123@localhost:27017/blog
services:
  mongo:
    image: mongo:4.4
    container_name: mongodb
    environment:
      # 数据库管理员账户配置
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME:-blog} # 默认使用 'blog'
    volumes:
      - ${HOME}/docker-apps/mongodb/data:/data/db
      - ${HOME}/docker-apps/mongodb/backup:/data/backup
      # 一次性的初始化脚本
      - ${HOME}/docker-apps/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    expose:
      - "27017"
    # ports:
    #   - "27017:27017"
    command: --auth
    networks:
      database-network:
        aliases:
          - mongodb

networks:
  database-network:
    external: true
