# version: '3.8'

# docker compose -f ./docker-compose.minio.yml -p local-minio up -d
# 重启服务
# docker compose -f ./docker-compose.minio.yml -p local-minio restart minio
services:
  minio:
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    # image: minio/minio:RELEASE.2023-12-23T07-19-11Z
    container_name: minio
    expose:
      - "9000"
      - "9001"
    # ports: # 测试端口
    #   - "9000:9000"
    #   - "9001:9001"
    environment:
      # minio登录用户名
      MINIO_ACCESS_KEY: admin
      # minio登录密码
      MINIO_SECRET_KEY: admin123
      MINIO_HTTPS_ENABLE: 'true'
      MINIO_CERTS_CERTIFICATE: /certs/public.crt
      MINIO_CERTS_PRIVATE_KEY: /certs/private.key
    volumes:
      - ${HOME}/docker-apps/minio/data:/data
      - ${HOME}/docker-apps/minio/config:/root/.minio
      - ${HOME}/docker-apps/minio/certs:/certs:ro
    command: server /data
    networks:
      - storage-network
      - backend-network

networks:
  storage-network:
    name: storage-network
    external: true
  backend-network:
    name: backend-network
    external: true

# mkdir certs
# openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
#   -keyout certs/private.key -out certs/public.crt \
#   -subj "/C=US/ST=State/L=City/O=Organization/CN=smallpig.site"
