version: '3.8'

# volumes:
# - docker-apps
#   - frontend-dist
#   - backend-dist
#   - mongo-data
#   - redis-data
#   - nginx-certs 对应 nginx/certs
#   - nginx-conf 对应 nginx/nginx.conf
#   - certbot-webroot
# - docker-backups

services:
  web:
    container_name: nginx-web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-certs:/etc/nginx/ssl
      - nginx-conf:/etc/nginx/nginx.conf
      - frontend-dist:/usr/share/nginx/html
      - certbot-webroot:/var/www/certbot
    depends_on:
      - api
      - certbot
    networks:
      - frontend
      - backend

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - nginx-certs:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email admin@x.com --agree-tos --no-eff-email -d x.com -d www.x.com
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  api:
    image: node:18-alpine
    container_name: nestjs-api
    working_dir: /app
    volumes:
      - backend-dist:/app
    command: npm run start:prod
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/app
      - REDIS_URI=redis://redis:6379
    depends_on:
      - mongo
      - redis
    networks:
      - backend

  mongo:
    image: mongo:4.4
    container_name: mongodb
    volumes:
      - mongo-data:/data/db
      - mongo-backup:/backup
    networks:
      - backend

  mongo-backup:
    image: mongo:4.4
    container_name: mongodb-backup
    volumes:
      - mongo-backup:/data/backup
    depends_on:
      - mongo
    networks:
      - backend
    command: |
      /bin/sh -c '
      while true; do
        echo "[$(date)] Starting backup..."
        mongodump --host mongo --out /data/backup/$(date +%Y%m%d_%H%M%S)
        echo "[$(date)] Backup completed"
        sleep 24h
      done
      '

  redis:
    image: redis:alpine
    container_name: redis-cache
    volumes:
      - redis-data:/data
    networks:
      - backend

networks:
  frontend:
  backend:

# 虽然服务被拆分到不同的 docker-compose 文件中，但可以通过 Docker 网络将它们连接起来。
# 再拆分的 compose 文件中，分别添加 external 网络配置，将服务连接到相应的网络。
# networks:
#   frontend-network:
#     external: true  # 使用外部网络
#   backend-network:
#     external: true  # 使用外部网络

volumes:
  nginx-certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/docker-apps/nginx/certs
  nginx-conf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/docker-apps/nginx/nginx.conf
  backend-dist:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/docker-apps/backend-dist
  frontend-dist:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/docker-apps/frontend-dist
  mongo-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/docker-apps/mongo-data
  redis-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/docker-apps/redis-data
  certbot-webroot:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/docker-apps/certbot-webroot
  mongo-backup:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/docker-backups/mongo-backup
