version: '3.8'

# 备注
# 暂不使用监控相关服务，后续再考虑
services:
  # Nginx 网关服务
  gateway:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "9091:9091"
    volumes:
      - ./gateway.nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./certbot:/var/www/certbot:ro
      - ./logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
        max_attempts: 3

  # 前端服务
  frontend:
    image: nginx:alpine
    expose:
      - "80"
    volumes:
      - ../dist:/usr/share/nginx/html:ro
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
      restart_policy:
        condition: on-failure

  # 后端服务
  backend:
    image: node:18-alpine
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ../backend:/app
    command: ["node", "app.js"]
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure

  # Prometheus 监控服务
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Grafana 可视化监控
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M

  # ELK 日志收集
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.3
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    depends_on:
      - elasticsearch
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M

  # Consul 服务发现
  consul:
    image: consul:latest
    ports:
      - "8500:8500"
    command: agent -server -bootstrap-expect=1 -ui -client=0.0.0.0
    volumes:
      - consul_data:/consul/data
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M

volumes:
  prometheus_data:
  grafana_data:
  elasticsearch_data:
  consul_data:
